=== fersanzenrique-cell/learningCode/out/production/learningCode/Lenguajes de marcas/UD06/Practica/aviones.dtd
<!ELEMENT hangar (aviones, helicopteros, drones)>
<!ATTLIST hangar geolocalizacion CDATA #REQUIRED>

<!ELEMENT aviones (avion+)>
<!ELEMENT avion (asignacion+)>
<!ATTLIST avion tipo CDATA #REQUIRED>

<!ELEMENT helicopteros (heli+)>
<!ELEMENT heli (asignacion+)>
<!ATTLIST heli tipo CDATA #REQUIRED>

<!ELEMENT drones (dron+)>
<!ELEMENT dron (asignacion+)>
<!ATTLIST dron tipo CDATA #REQUIRED>

<!ELEMENT asignacion (informacion)>
<!ATTLIST asignacion nombre-nato CDATA #REQUIRED>

<!ELEMENT informacion (radar-signature, radar-distance, areal-range, top-speed, armamento, desc)>
<!ATTLIST informacion veridica (True|False) "True">

<!ELEMENT radar-signature (#PCDATA)>
<!ATTLIST radar-signature es-sigilo (Yes|No) #REQUIRED>

<!ELEMENT radar-distance (#PCDATA)>
<!ATTLIST radar-distance tipo CDATA #REQUIRED>

<!ELEMENT areal-range (#PCDATA)>
<!ATTLIST areal-range has-air-refueling (Yes|No) #REQUIRED>

<!ELEMENT top-speed (#PCDATA)>
<!ATTLIST top-speed has-afterburner (Yes|No) #REQUIRED>

<!ELEMENT armamento (aire-tierra, aire-aire)>

<!ELEMENT aire-tierra (misiles*, gravedad*, rifle*)>
<!ELEMENT aire-aire (misiles*, rifle*)>

<!ELEMENT misiles (#PCDATA)>
<!ELEMENT gravedad (#PCDATA)>
<!ELEMENT rifle (#PCDATA)>

<!ELEMENT desc (#PCDATA)>
<!ATTLIST desc generacion CDATA #REQUIRED>

=== fersanzenrique-cell/learningCode/Lenguajes de marcas/UD06/Practica/aviones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--La práctica ira vehiculos de aire militares y como queremos guardar datos sobre ellos-->
<!DOCTYPE aviones SYSTEM "aviones.dtd">
<hangar geolocalizacion="40.4168,-3.7038"> <!--Madrid, España-->
    <aviones>
        <avion tipo="superioridad-aerea">
            <asignacion nombre-nato="Typhoon">
                <informacion veridica="True">
                    <radar-signature es-sigilo="No">0.5</radar-signature> 
                    <!--En metros cuadrados RCS aproximado-->
                    <radar-distance tipo="CAPTOR-E AESA">200 km</radar-distance>
                    <areal-range has-air-refueling="Yes">2900 km</areal-range>
                    <top-speed has-afterburner="Yes">Mach 2.0</top-speed>
                    <armamento>
                        <aire-tierra>
                           <misiles>Brimstone</misiles> 
                           <gravedad>Paveway IV</gravedad>
                           <rifle>27mm Mauser BK-27</rifle>
                        </aire-tierra>
                        <aire-aire>
                            <misiles>AIM-120 AMRAAM</misiles>
                            <misiles>IRIS-T</misiles>
                            <rifle>27mm HEI</rifle>
                        </aire-aire>
                    </armamento>
                    <desc generacion="4.5">Caza de superioridad aérea europeo bimotor altamente maniobrable.</desc>
                </informacion>
            </asignacion>
            <asignacion nombre-nato="Raptor">
                <informacion veridica="True">
                    <radar-signature es-sigilo="Yes">0.0001</radar-signature>
                    <radar-distance tipo="AN/APG-77 AESA">240 km</radar-distance>
                    <areal-range has-air-refueling="Yes">2960 km</areal-range>
                    <top-speed has-afterburner="Yes">Mach 2.25</top-speed>
                    <armamento>
                        <aire-tierra>
                           <misiles>GBU-32 JDAM</misiles> 
                           <gravedad>GBU-39 SDB</gravedad>
                           <rifle>20mm M61A2 Vulcan</rifle>
                        </aire-tierra>
                        <aire-aire>
                            <misiles>AIM-120C AMRAAM</misiles>
                            <misiles>AIM-9X Sidewinder</misiles>
                            <rifle>20mm HE</rifle>
                        </aire-aire>
                    </armamento>
                    <desc generacion="5">Caza furtivo de quinta generación con supercrucero.</desc>
                </informacion>
            </asignacion>
        </avion>

        <avion tipo="cas"> <!--close air support-->
            <asignacion nombre-nato="Warthog">
                <informacion veridica="True">
                    <radar-signature es-sigilo="No">1.0</radar-signature>
                    <radar-distance tipo="AN/APG-66 mod">150 km</radar-distance>
                    <areal-range has-air-refueling="Yes">4150 km</areal-range>
                    <top-speed has-afterburner="No">706 km/h</top-speed>
                    <armamento>
                        <aire-tierra>
                           <misiles>AGM-65 Maverick</misiles> 
                           <gravedad>MK-82</gravedad>
                           <rifle>30mm GAU-8 Avenger</rifle>
                        </aire-tierra>
                        <aire-aire>
                            <misiles>AIM-9 Sidewinder</misiles>
                            <rifle>30mm API</rifle>
                        </aire-aire>
                    </armamento>
                    <desc generacion="4">Avión especializado en apoyo aéreo cercano y ataque a tierra.</desc>
                </informacion>
            </asignacion>
        </avion>

        <avion="multirol">
            <asignacion nombre-nato="Lightning II">
                <informacion veridica="True">
                    <radar-signature es-sigilo="Yes">0.0015</radar-signature>
                    <radar-distance tipo="AN/APG-81 AESA">220 km</radar-distance>
                    <areal-range has-air-refueling="Yes">2800 km</areal-range>
                    <top-speed has-afterburner="Yes">Mach 1.6</top-speed>
                    <armamento>
                        <aire-tierra>
                           <misiles>AGM-158 JASSM</misiles> 
                           <gravedad>GBU-53 SDB II</gravedad>
                           <rifle>25mm GAU-22/A</rifle>
                        </aire-tierra>
                        <aire-aire>
                            <misiles>AIM-120D AMRAAM</misiles>
                            <misiles>AIM-9X</misiles>
                            <rifle>25mm HEI</rifle>
                        </aire-aire>
                    </armamento>
                    <desc generacion="5">Caza multifunción furtivo con sensores fusionados.</desc>
                </informacion>
            </asignacion>
        </avion>
    </aviones>

    <helicopteros>
        <heli="recon">
            <asignacion nombre-nato="Kiowa">
                <informacion veridica="True">
                    <radar-signature es-sigilo="No">2.0</radar-signature>
                    <radar-distance tipo="Mast Mounted Sight">50 km</radar-distance>
                    <areal-range has-air-refueling="No">480 km</areal-range>
                    <top-speed has-afterburner="No">240 km/h</top-speed>
                    <armamento>
                        <aire-tierra>
                           <misiles>AGM-114 Hellfire</misiles> 
                           <rifle>12.7mm M3P</rifle>
                        </aire-tierra>
                        <aire-aire>
                            <misiles>Stinger</misiles>
                            <rifle>7.62mm</rifle>
                        </aire-aire>
                    </armamento>
                    <desc generacion="3">Helicóptero ligero de reconocimiento armado.</desc>
                </informacion>
            </asignacion>
        </heli>

        <heli="ataque">
            <asignacion nombre-nato="Apache">
                <informacion veridica="True">
                    <radar-signature es-sigilo="No">1.8</radar-signature>
                    <radar-distance tipo="AN/APG-78 Longbow">100 km</radar-distance>
                    <areal-range has-air-refueling="No">480 km</areal-range>
                    <top-speed has-afterburner="No">293 km/h</top-speed>
                    <armamento>
                        <aire-tierra>
                           <misiles>AGM-114 Hellfire</misiles> 
                           <gravedad>Hydra 70</gravedad>
                           <rifle>30mm M230</rifle>
                        </aire-tierra>
                        <aire-aire>
                            <misiles>Stinger</misiles>
                            <rifle>30mm HE</rifle>
                        </aire-aire>
                    </armamento>
                    <desc generacion="4">Helicóptero de ataque pesado con radar Longbow.</desc>
                </informacion>
            </asignacion>
        </heli=ataque>
    </helicopteros>

    <drones>
        <dron="bombardero">
            <asignacion nombre-nato="Reaper">
                <informacion veridica="True">
                    <radar-signature es-sigilo="No">0.3</radar-signature>
                    <radar-distance tipo="AN/APY-8 Lynx">80 km</radar-distance>
                    <areal-range has-air-refueling="No">1850 km</areal-range>
                    <top-speed has-afterburner="No">482 km/h</top-speed>
                    <armamento>
                        <aire-tierra>
                           <misiles>AGM-114 Hellfire</misiles> 
                           <gravedad>GBU-12</gravedad>
                        </aire-tierra>
                        <aire-aire></aire-aire>
                    </armamento>
                    <desc generacion="4">UAV MALE de vigilancia y ataque de larga duración.</desc>
                </informacion>
            </asignacion>
        </dron>

        <dron="kamikaze">
            <asignacion nombre-nato="Shahed-136">
                <informacion veridica="True">
                    <radar-signature es-sigilo="No">0.6</radar-signature>
                    <radar-distance tipo="GPS guiado">40 km</radar-distance>
                    <areal-range has-air-refueling="No">2500 km</areal-range>
                    <top-speed has-afterburner="No">185 km/h</top-speed>
                    <armamento>
                        <aire-tierra>
                           <misiles>Carga explosiva integrada</misiles> 
                        </aire-tierra>
                        <aire-aire></aire-aire>
                    </armamento>
                    <desc generacion="3">Munición merodeadora de largo alcance tipo kamikaze.</desc>
                </informacion>
            </asignacion>
        </dron>
    </drones>
</hangar>
