=== fersanzenrique-cell/learningCode/Lenguajes de marcas/UD06/1.dtd
<!ELEMENT libro (titulo,autor,ano-publicacion,resumen?,capitulos)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (nombre,apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT ano-publicacion (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>
<!ELEMENT capitulos (capitulo+)>
<!ELEMENT capitulo (numero,titulo-cap)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT titulo-cap (#PCDATA)>

=== fersanzenrique-cell/learningCode/out/production/learningCode/Lenguajes de marcas/UD06/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro SYSTEM "1.dtd">
<libro>
    <titulo>
        Lo que el viento se llev√≥
    </titulo>
    <autor>
        <nombre>Cristina</nombre>
        <apellidos>Rebollo</apellidos>
    </autor>
    <ano-publicacion>2025</ano-publicacion>
    <resumen></resumen>
    <capitulos>
        <capitulo>
            <numero>1</numero>
            <titulo-cap>Capitulo1</titulo-cap>
        </capitulo>
    </capitulos>
</libro>
