<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
    <!ELEMENT agenda (contacto*)>
    <!ELEMENT contacto (nombre, telefonoFijo+, telefonoMovil*)>
    <!--telefonoMovil, no esta declarado y poniendole * hago que sea (0,n)
    telefonoFijo aparecerá (1,n) con +-->
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT telefonoFijo (#PCDATA)>
    <!ELEMENT telefonoMovil (#PCDATA)>
]>
<agenda>
    <contacto>
        <nombre>Ayuntamiento</nombre>
        <telefonoFijo>010</telefonoFijo>
    </contacto>
    <contacto>
        <nombre>Emergencias</nombre>
        <telefonoFijo>112 (Unión Europea)</telefonoFijo>
        <telefonoFijo>911 (Estados Unidos)</telefonoFijo>
        <telefonoMovil>Desconocido</telefonoMovil>
        <!--telefonoFijo no estaba en el buen orden-->
    </contacto>
</agenda>