=== fersanzenrique-cell/learningCode/Lenguajes de marcas/UD06/Practica sus 2/empleados.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empleados">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="empleado" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="apellido" type="xs:string"/>
                            <xs:element name="edad" type="xs:integer"/>
                            <xs:element name="departamento" type="xs:string"/>
                            <xs:element name="cargo" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== fersanzenrique-cell/learningCode/Lenguajes de marcas/UD06/Practica sus 2/empleados.xml
<?xml version="1.0" encoding="UTF-8"?>
<empleados xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="empleados.xsd" >
    <empleado>
        <nombre>Ana</nombre>
        <apellido>García</apellido>
        <edad>30</edad>
        <departamento>Ventas</departamento>
        <cargo>Ejecutivo de ventas</cargo>
    </empleado>
    <empleado>
        <nombre>Luis</nombre>
        <apellido>Rodríguez</apellido>
        <edad>45</edad>
        <departamento>Finanzas</departamento>
        <cargo>Analista financiero</cargo>
    </empleado>
    <empleado>
        <nombre>María</nombre>
        <apellido>López</apellido>
        <edad>28</edad>
        <departamento>Marketing</departamento>
        <cargo>Especialista en redes sociales</cargo>
    </empleado>
</empleados>
