=== fersanzenrique-cell/learningCode/out/production/learningCode/Lenguajes de marcas/UD06/Practicas DTD/Actividad2/1/ej1.dtd
<!-- UD06. DTD Ejercicios
1. Escribe un DTD para describir la estructura de un archivo XML que represente un libro con las
siguientes características:
• Un libro tiene un título, un autor (nombre y apellido) y un año de publicación.
• Opcionalmente, puede incluir un resumen.
• Puede tener uno o varios capítulos. Cada capítulo tiene un número y un título.
-->
<!ELEMENT libro (titulo,autor,year-publicacion,resumen?,capitulo*)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (nombre,apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT year-publicacion (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>
<!ELEMENT capitulo (numero)>
<!ATTLIST capitulo cap-titulo CDATA "">
<!ELEMENT numero (#PCDATA)>

=== fersanzenrique-cell/learningCode/out/production/learningCode/Lenguajes de marcas/UD06/Practicas DTD/Actividad2/1/ej1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro SYSTEM "ej1.dtd">
<libro>
    <titulo></titulo>
    <autor>
        <nombre></nombre>
        <apellido></apellido>
    </autor>
    <year-publicacion></year-publicacion>
    <resumen></resumen>
    <capitulo cap-titulo="">
        <numero></numero>
    </capitulo>
</libro>
